apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fincra-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/masterminders-maker/fincra-take-home.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


SELECT role, COUNT(*) AS count FROM users GROUP BY role ORDER BY role; SELECT COUNT(*) AS stores FROM stores; SELECT COUNT(*) AS riders FROM riders; SELECT COUNT(*) AS orders FROM orders; SELECT COUNT(*) AS products FROM products;
